### ISSUE TITLE
Proportion of delinquent tax dollars are owed by commercial parcels

### ISSUE THREAD

**Issue by cdamoah** [Watts-College/cpp-526-fall-2022#10]
Question 7b asks for proportion of delinquent tax dollars owed by commercial parcels and I am thinking the code is

mean(downtown$amtdelinqt & downtown$landuse =="Commercial")/downtown$amtdelinqt    but it output is not anything meaningful. 

Should it be like this instead mean(downtown$amtdelinqt & downtown$landuse =="Commercial")/ mean(downtown$amtdelinqt) 

@jacobtnyoung

**Comment by jacobtnyoung** [comment]
Hi @cdamoah. For the first statement, you are dividing by a vector. In the second you have a scalar (a single number). See the difference?

Also, be sure to recheck the instructions for adding code to Issues. It makes it much easier to help if it is displayed as R code. 

Let me know if you still have questions!

**Comment by jacobtnyoung** [comment]
Like this:

`mean(downtown$amtdelinqt & downtown$landuse =="Commercial")/ mean(downtown$amtdelinqt)`

**Comment by danafuller** [comment]
This code:
mean(downtown$amtdelinqt & downtown$landuse =="Commercial")/ mean(downtown$amtdelinqt)
Is giving me this result:
[1] 4.95445e-06
Which is a very small number.  How do I correctly translate into percentage?  It can't be 4.6% can it?

**Comment by jacobtnyoung** [comment]
Hi @danafuller!

You will need to rework the code you have:

`mean(downtown$amtdelinqt & downtown$landuse =="Commercial")/ mean(downtown$amtdelinqt)`

Think about what the numerator should be and what the denominator should be conceptually. Then translate that to logical statements. 

Let me know if you are still struggling with it.

**Comment by danafuller** [comment]
I think it should be the number of tax delinquent properties that are commercial divided by the total number of commercial properties.
mean(downtown$amtdelinqt)& mean(downtown$landuse =="Commercial")/mean(downtown$landuse =="Commercial")

This second one  is the tax dollars owed by commercial properties (a subset) over all tax dollars owed.  How do you capture the total number of tax dollars owed.  Do I need to add in the variables: countytaxbl, schooltxbl, and citytaxbl.able   Also, it looks like the only variable that captures all tazes is one that only captures the delinquent taxes.  This code is wrong below because I don't have the answers to those questions.  I am hoping I can rework it with that info.  Thank you!
all.commerical<-downtown$landuse == "Commercial"  
mean(all.commercial)/mean(downtown$amtdelinqt)

**Comment by danafuller** [comment]
I forgot to add that this:
mean(downtown$amtdelinqt)& mean(downtown$landuse =="Commercial")/mean(downtown$landuse =="Commercial")
Was printing out this:
[1] TRUE

**Comment by jacobtnyoung** [comment]
Hi @danafuller, 

You need to enclose the conditional statements and you need to define the groups a bit differently. Your code:

```
 mean(downtown$amtdelinqt)& mean(downtown$landuse =="Commercial")/mean(downtown$landuse =="Commercial")
```
says to calculate a mean, and a mean, then divide by a mean.

Compare your code to this statement:

```
downtown$amtdelinqt != 0 & downtown$landuse =="Commercial"
```
If you type this out it will show you the T and F for cases that meet this condition. That is, cases for which the amount delinquent is not equal to 0 and land use is commercial.

Do you see the difference?

Then, you can build from there:

```
sum( downtown$amtdelinqt != 0 & downtown$landuse =="Commercial" ) / sum(downtown$landuse =="Commercial")
```

Here, the numerator is the count of commercial properties that have delinquent accounts and the denominator is the count of commercial properties.

Make sense?

**Comment by danafuller** [comment]
Yes, I just feel like is a total mind bender when I am trying to figure it out, lol.  Thank you for saving my sanity!

**Comment by danafuller** [comment]
Although, I am confused why these are the instructions:
# Use function: 'mean()'
# Use variable: 'amtdelinqt'
# Use variable: 'landuse'

Should the first one say Use Function sum() instead?

**Comment by lecy** [comment]
When you apply mathematical functions to logical vectors it converts TRUE and FALSE to 1 and 0. 

The sum of 1's and 0's will give you the total number of cases that meet the requirement. 

The mean of 1's and 0's will give you the proportion of the sample that meets your criteria. 

```r
x <- 1:10
sum( x > 7 )  # 3
mean( x > 7 )  # 0.3

# the mean is equivalent to but easier than:
sum( x > 7 ) / length(x) 
```

http://ds4ps.org/dp4ss-textbook/p-050-business-logic.html#selector-vectors

**Comment by jacobtnyoung** [comment]
Thansk @lecy!

**Comment by danafuller** [comment]
I appreciate the post @lecy!
