### ISSUE TITLE
Lab 2 Question 3

### ISSUE THREAD

**Issue by amandaripstra** [Watts-College/cpp-526-fall-2022#11]
This seems like a simple question and yet I'm lost.
I am unable to find the number of constructed either after or during and after than 1980. I would guess I'm not using the right function, but I'm not sure what function to use. I was able to produce a table of years with the second function, but that doesn't answer the question.

```{r}
sum (downtown$yearbuilt == ">=1980")

downtown$yearbuilt

**Comment by amandaripstra** [comment]
I think I figured it out - used summary instead of sum

**Comment by jacobtnyoung** [comment]
Hi @amandaripstra! Good question. In this statement you have this:

`sum (downtown$yearbuilt == ">=1980")`

Here is how it should read:

`sum(downtown$yearbuilt >= "1980")`

Note the differences: 1) there is not a space between `sum` and the `(`; 2) the operator is outside the quotes. In the first statement it reads: "exactly equal to ">=1980". R is looking for that exact character in the `yearbuilt` column.

Does that make sense?

**Comment by amandaripstra** [comment]
Hi @jacobtnyoung - 

```r
sum(downtown$yearbuilt >= "1980") 
```
gave me [1] NA
but 
```r
summary(downtown$yearbuilt >= 1980)
```
gave me true and false totals for number of buildings - is that okay to use?

I'm stuck on another question - should I start a new issue?

**Comment by jacobtnyoung** [comment]
Hi @amandaripstra!

If you use `downtown$yearbuilt >= "1980"`, you will see that there are missing values for this variable. So, when you ask R to perform the `sum()` function, it returns NA.

So, just be sure to set the `na.rm=` argument to `TRUE` as in:

`sum( downtown$yearbuilt >= "1980",na.rm = TRUE )`

**Comment by jacobtnyoung** [comment]
Also @amandaripstra, `summary()` is going to summarize the data and not give you what you want. So, just use `sum()` as in the prior comment.

**Comment by jacobtnyoung** [comment]
Hi @amandaripstra. 

You can start another issue. that is fine.

**Comment by amandaripstra** [comment]
Thanks, @jacobtnyoung. I think I figured it out. I may have done everything the hard way, since I didn't scroll the length of the instructions (ugh, duh!)

**Comment by jacobtnyoung** [comment]
Hi @amandaripstra! No worries. Well, if that is the case, then it is a lesson you only have to learn once! :)
