### ISSUE TITLE
Plotting specific areas

### ISSUE THREAD

**Issue by alinemaestas** [Watts-College/cpp-526-fall-2022#12]
Hi Professor,
I need help with plotting specific areas in general. I'm already stuck on question 1 since I am not plotting on the geographical area correctly.
plot( downtown,  border="gray50", col="gray80" ) 
plot(downtown$landuse=="Vacant Land", border = "gray50", col="lightpink") 

<img width="427" alt="image" src="https://user-images.githubusercontent.com/112110787/187508095-8f7c2e52-88bf-4e15-9584-fda044eb68eb.png">

**Comment by jacobtnyoung** [comment]
Hi @alinemaestas!

It looks like you need to load the appropriate libraries:

`
library( geojsonio )
library( sp )
library( rgdal )
`

After doing this, execute the first statement you have: `plot( downtown, border="gray50", col="gray80" )`

**Comment by jacobtnyoung** [comment]
Hi @alinemaestas, that should read like this:

```
library( geojsonio )
library( sp )
library( rgdal )
```

**Comment by jacobtnyoung** [comment]
Then @alinemaestas, take a look through the entire lab as there are some suggestions for aiding with plotting.

For example, your second statement above you can use:

```
these <- downtown$landuse == "Vacant Land"
group.colors <- ifelse( these, "lightpink", "gray80" )
plot( downtown,  border="gray70", col=group.colors )
```

Note the difference in the call to the `plot()` function. Here, it is calling the object `downtown`. This is important for producing the spatial map.

**Comment by alinemaestas** [comment]
Thank you!!

<img width="365" alt="image" src="https://user-images.githubusercontent.com/112110787/187589227-6bc69391-249d-4f73-9701-89a77bffda2b.png">

**Comment by jacobtnyoung** [comment]
Of course @alinemaestas
