### ISSUE TITLE
Question 5-# of delinquent tax parcels

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#13]
The instructions for this problem lists this:
# Use function: 'sum()'
# Use variable: 'amtdelinqt'

I used this code:
sum(downtown$amtdelinqt)
[1] 5045969
When I look at the actual column under that variable it shows 9 parcels that are delinquent and they do not add up to that dollar amount either.

**Comment by jacobtnyoung** [comment]
It is summing up the variable. You can see this using:

`downtown$amtdelinqt`

**Comment by danafuller** [comment]
Thank you

**Comment by jacobtnyoung** [comment]
Of course! @danafuller

**Comment by danafuller** [comment]
Sorry to open this back up, but it still isn't working out for me.  This is what I am seeing as the output.  I can't figure out a way to sum it without getting the above results that I already posted about.  
downtown$amtdelinqt
  [1]       0.00       0.00       0.00
  [4]       0.00       0.00       0.00
  [7]       0.00       0.00       0.00
 [10]       0.00   15106.84       0.00
 [13]       0.00       0.00       0.00
 [16]       0.00       0.00     838.70

**Comment by danafuller** [comment]
@jacobtnyoung I am not sure if the above would notify you since it was closed unless I tagged you, so I am trying that.

**Comment by jacobtnyoung** [comment]
Hi @danafuller. You might post a screen shot. It looks like you have might have changed the downtown data object. Try typing this:

```
rm( list = ls() ) # to clear the workspace

#load the libraries.
library( geojsonio )
library( sp )
library( rgdal )

#load the data.
URL <- "https://raw.githubusercontent.com/DS4PS/Data-Science-Class/master/DATA/downtown-syr.geojson"
downtown <- geojson_read( URL, what="sp" )

# now show the variable:
downtown$amtdelinqt
```

This should print out the variable `amtdelinqt` for each row of the data file.

**Comment by danafuller** [comment]
I did all of the above and it yielded the same result.  I just attached 3 screenshots because it just continued sequentially until a section labeled 388.  Does this make sense?
![2022-08-31](https://user-images.githubusercontent.com/89417938/187758985-59343827-fb8a-44a9-be09-ccd1f114a77f.png)
![2022-08-31 (1)](https://user-images.githubusercontent.com/89417938/187759074-d1f2487c-65e2-4a61-a349-51afc5bbf0b2.png)
![2022-08-31 (2)](https://user-images.githubusercontent.com/89417938/187759144-8ff18ccc-3141-46d8-a871-0e4a3e14969e.png)

**Comment by jacobtnyoung** [comment]
Hi @danafuller! I see. It is printing out correctly. It just cuts it to three columns in the print out because of how large the text is. 

What it is printing is a vector. it just displays that way.

But, I am still not sure what your question is. Perhaps you could clarify. (sorry!)

**Comment by danafuller** [comment]
No problem!  I think the question is asking the **number** of delinquent tax parcels.  So I am assuming there is code that sums it up like sum(), but that is not adding the number of parcels.  I can count them manually, but I don't think that is what you are looking for?

**Comment by jacobtnyoung** [comment]
@danafuller you can use `sum()`, like this: `sum(downtown$amtdelinqt)` but that returns the sum of the amounts.

If you want a count, you need to specify a condition. Something like: `sum(downtown$amtdelinqt != 0)`

**Comment by danafuller** [comment]
!= This operator is really throwing me off.  Sorry and thanks!

**Comment by jacobtnyoung** [comment]
Hi @danafuller. You might want to review the operators from the readings for this week. The `!=` operation says "not equal to". So `sum( downtown$amtdelinqt != 0 )` says to sum the values of `downtown$amtdelinqt` for cases in which it is not equal to zero. Make sense?
