### ISSUE TITLE
rmd to html

### ISSUE THREAD

**Issue by AliciaSettles** [Watts-College/cpp-526-fall-2022#14]
Hello,

I have my lab, it includes images that match the lab instructions based on my code, however when I knit my .rmd file into an html it does not include the images, it only saves and displays the code. The .rmd file does have the images though so I am not sure how to save the .html file to include everything. Thanks!

**Comment by jacobtnyoung** [comment]
Hi @AliciaSettles! Send me your .Rmd file to CPP526@asu.edu. I will take a look on my end.

**Comment by jacobtnyoung** [comment]
Hi @AliciaSettles! Thanks for sending the .Rmd file. There are two issues. 

1. You need to set the argument `eval=` to `TRUE` in your code chunk. Right now you have this:

```
{r eval=FALSE}
```
So R is printing out the code, but not evaluating the code (i.e. executing).

2. You need to import the data. If you set `eval=TRUE` you will get an error. This is because you have not loaded the data. See the lab 2 instructions as well as the template for the code to do this.

Let me know if you are still having issues.

**Comment by AliciaSettles** [comment]
Hi Professor,

Thank you for your response!  I attempted to do just that, I took a look at it and the bottom of lab 02, which is slightly confusing me with "add eval = FALSE inside the brackets of {r} at the beginning of a chunk to ensure that R does not attempt to evaluate it, that is: {r eval = FALSE}. This will prevent an erroneous chunk of code from halting the knitting process." 

What I am getting is an error for every chunk when I go to execute it that says "Error in unique (downtown$landuse) : object 'downtown' not found. Calls: <Anonymous>...withVisible -> eval_with_user_handlers -> eval -> unique Execution halted. 

I think that is the error you were stating in your response, however I am not sure where to set the argument as eval = TRUE versus the where not to in order to prevent the error.

**Comment by jacobtnyoung** [comment]
HI @AliciaSettles. You are getting that error because you have not loaded the data. You need to tell R to load the data when executing the .Rmd file.

You need to add this as a code chunk or part of a code chunk:

```
URL <- "https://raw.githubusercontent.com/DS4PS/Data-Science-Class/master/DATA/downtown-syr.geojson"
downtown <- geojson_read( URL, what="sp" )
```

Then the data will be loaded.

**Comment by AliciaSettles** [comment]
Hi Professor,

I included that in my code chunk but I am receiving an error saying that there's an error in geojson_read(URL, what "sp") : could not find function 'geojson_read" 

Which is what is also halting the execution, since the data is loaded and I am still receiving that error, I believe that's where I remained confused. Thanks again for your help!

**Comment by jacobtnyoung** [comment]
Hi @AliciaSettles.

You also need to load the libraries.

```
library( geojsonio )
library( sp )
library( rgdal )
```

Then, you need to add this to your script:

```
downtown <- geojson_read( URL, what="sp" )
```

**Comment by jacobtnyoung** [comment]
See the prior point. You need to load the libraries and the data.

**Comment by jacobtnyoung** [comment]
@AliciaSettles I added the code above to your script and it worked.

**Comment by AliciaSettles** [comment]
Ah! Thank you, it has worked for me now. I see that I included the data and that it was imported but I did not load the libraries in the code chunk. My apologies, thank you so much for the clarification. I will make note of this. I do appreciate your help and time.

**Comment by jacobtnyoung** [comment]
Hi @AliciaSettles! Glad you got it to work. No worries, it can be maddening when you can't figure out something like this. Been there!
