### ISSUE TITLE
general questions about procedures before and after R sessions

### ISSUE THREAD

**Issue by cjstewa9** [Watts-College/cpp-526-fall-2022#15]
I was just wondering what good procedures were before and after an R session. 

- In STATA, it's good practice to use the command "clear" before and after a session. Before your next session, you simply run your do file to get to where you were. This process means one doesn't have to have 10 iterations of data saved on their computer. Is this a good thing to do in R as well? If so, is there a function that works similar to "clear" in STATA?
- How can I run only highlighted lines in an .rmd file? I tried to do this earlier by highlighting the lines I wanted to run and clicking "run selected lines" in the top right corner but it only ran the first chunk (I highlighted multiple chunks).

**Comment by jacobtnyoung** [comment]
You can use `rm( list = ls() )` to completely clear the workspace. 

You can only run particular chunks at a time. You can set `eval=FALSE` in the chunks you don't want to run and `eval=TRUE` in the chunks you do want to run and then execute the entire .Rmd file.

Does that help?
