### ISSUE TITLE
Loading Packages 

### ISSUE THREAD

**Issue by elowell1** [Watts-College/cpp-526-fall-2022#16]
For this second lab, I can get the first two packages to load but not the "geojsonio" package. Other than using install.package() or library(), is there another (less problematic) way to install packages? 

I did update my R this morning.

**Comment by jacobtnyoung** [comment]
Hi @elowell1. What is the error? Is is saying it can't load the package?

**Comment by elowell1** [comment]
I run the provided code to load the package and it never stops running. It will never complete the command.

**Comment by jacobtnyoung** [comment]
Did you reinstall R or RStudio? You should try reinstalling RStudio and see if you get the same error.
