### ISSUE TITLE
Lab #3 error message with points()

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#17]
I used this code to plot the avg strikeouts by team:
points(Teams$teamID, Teams$ave.so, pch=20, col.axis="gray60"),             # Size

I got his error:
Error: unexpected ',' in "points(Teams$teamID, Teams$ave.so, pch=20, col.axis="gray60"),"

I am unsure why it is giving me this.

**Comment by danafuller** [comment]
The default code written was this which yielded the same error message
points(x = year, 
       y = ave.so,
       col = "gray85",              # Color
       pch = 16,                    # Shape
       cex = 0.75)                  # Size

**Comment by danafuller** [comment]
Sorry, I have another question....Does this sufficiently limit the years in the data set?
plot.window(xlim = c(1900, 2012)

1. Limit years 1900 to 2012

**Comment by jacobtnyoung** [comment]
Hi @danafuller! So the second code chunk is giving you that error?

For your second question, yes that will restrict the window correctly.

**Comment by danafuller** [comment]
Yes, I get the error with that second chunk too. :(

**Comment by lecy** [comment]
The first is because of the comma at the end: 

```r
points( Teams$teamID, Teams$ave.so, pch=20, col.axis="gray60"),   # Size
```

You would need to provide a reproducible example for the second case to diagnose properly. 

Reproducible in this case would be starting with the canvas or plot functions (points appends to the original plot).

**Comment by jacobtnyoung** [comment]
Thanks @lecy :)

**Comment by jacobtnyoung** [comment]
Hi @danafuller!

See @lecy's point about creating a reproducible example. Also, make sure you review the [guidelines](https://watts-college.github.io/cpp-526-fall-2022/help/) for using github issues to get help. It makes it much easier to diagnose the issue if the code is correctly formatted.

**Comment by jacobtnyoung** [comment]
Hi @danafuller. I am not having any issues running the code from the lab. Here is what I have up to your question:

```
library(Lahman)
data(Teams)

ave.so <- Teams$SO / Teams$G # create the average strikeouts.

ave.so.min <- min( ave.so, na.rm=T ) #create the minimum strikeouts.
ave.so.max <- max( ave.so, na.rm=T ) #create the maximum strikeouts.

plot.new() # call the plot pane.

plot.window(xlim = c(1900, 2012), 
            ylim = c(ave.so.min, 
                     ave.so.max))   # Specify dimensions

points(x = year, 
       y = ave.so)                  # Plot points

```

You should be able to copy and paste directly from this post and have this render the following plot:

![image](https://user-images.githubusercontent.com/39632608/188732454-558dd103-0806-4fc9-b331-7791cd683d6f.png)

**Comment by danafuller** [comment]
Thank you so much.  I will review the guidelines to make it easier next time!

**Comment by jacobtnyoung** [comment]
👍🏼
