### ISSUE TITLE
Lab #3 Knitting issues

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#20]
I am getting this warning message 
![2022-09-07 (1)](https://user-images.githubusercontent.com/89417938/189031229-12d2b19b-9cc2-47d4-9506-c81ae4be4869.png)
![2022-09-07](https://user-images.githubusercontent.com/89417938/189031248-7fc51944-1cff-4f30-a6e6-037d8b270ba1.png)

I am apparently a mess tonight

**Comment by lecy** [comment]
Rtools is a set of compilers used to create new packages, so it has to be installed slightly differently. 

https://cran.r-project.org/bin/windows/Rtools/

Also remember to only load packages inside of chunks, not install them. If you try to knit with an install.packages() call inside the RMD you will get errors or it can freeze. 

Install once. Load with library() after that. 

R is fun.

**Comment by danafuller** [comment]
R is fun.  I appreciate your help!

**Comment by lecy** [comment]
👍

**Comment by jacobtnyoung** [comment]
Thanks @lecy!

**Comment by jacobtnyoung** [comment]
@danafuller did you get this to knit? I didn't see an html file.

**Comment by jacobtnyoung** [comment]
Hi @danafuller. The error in your code is the one @lecy identified above. If you go to line 14 of your .Rmd file, you will see that you are executing the command: `install.packages("dplyr")`. As @lecy indicated, you need to exclude this from knitting.

Be sure to review the Mardown basics [video](https://www.youtube.com/watch?v=oXgFrUq6btQ&feature=youtu.be).

**Comment by jacobtnyoung** [comment]
@danafuller let's schedule a time during office hours to go through your .Rmd file.

**Comment by danafuller** [comment]
I would love that.  I did what Prof Lecy recommended and I still couldn't
knit.  I was out of ideas.  I will schedule with you on your page.  Thanks!

**Comment by jacobtnyoung** [comment]
Hi @danafuller I am available now.

**Comment by jacobtnyoung** [comment]
Hi @danafuller please check your email as will be blocked out of scheduling right now.
