### ISSUE TITLE
lab 03: how to connect text within the canvas to the point it's tied to

### ISSUE THREAD

**Issue by cjstewa9** [Watts-College/cpp-526-fall-2022#21]
In the NYT graphic, it looks like the historical annotations were tied to a point using the text() function. However, I couldn't figure out how s/he drew a line between the text and the point. The code for one of my historical annotations is...

```r

text(x = 1917, y = 3.48, 
     "U.S. enters \nWorld War I.", 
     col = "gray65", 
     pos = 1, 
     cex = 0.4, 
     offset = 3.2)

```

**Comment by jacobtnyoung** [comment]
Hi @cjstewa9! Take a look at the `segments()` function. You can use that to draw lines with fixed coordinates.
