### ISSUE TITLE
Lab 04: Error: Character argument expected 

### ISSUE THREAD

**Issue by courtney-haasch** [Watts-College/cpp-526-fall-2022#23]
I am receiving the following message when I attempt to Run Document: 
<img width="250" alt="Screen Shot 2022-09-13 at 9 19 05 PM" src="https://user-images.githubusercontent.com/104610526/190058866-e76fb20a-056c-4193-a27f-9fe37bd51ccb.png">

It was working before I tried to save my file.

In the console I see the following : Error in .rs.parsePackageDependencies(contents, extension) : 
  object 'partition_yaml_front_matter' not found

and render shows: Warning: Error in setwd: character argument expected

I am trying to save it but I want to make sure it will run before I submit.

**Comment by jacobtnyoung** [comment]
Hi @courtney-haasch! Try this:

1. Download the template again and click "Run Document" to make sure it renders the template correctly.

2. If 1. works correctly, then add your code into the template again. Start by building the plot before you add the functionality of then input$... operation.

3. If 2. works, then add the dynamic feature.

The hard part here is that without seeing all the code it is hard for me to diagnose the problem. If you work through it in pieces you should be able to identify the problem.

If you are still having issues, let me know and I will take a look through the .Rmd file.

**Comment by jacobtnyoung** [comment]
Hi @courtney-haasch! See the .Rmd file I sent back.
