### ISSUE TITLE
Error when going to run the document

### ISSUE THREAD

**Issue by AliciaSettles** [Watts-College/cpp-526-fall-2022#24]
Hi, everything was working fine I think, I could save the file and followed the instructions and handouts, however when I go to run the document, I get an error that says 

"Error: Can't modify read-only reactive value 'my_team'

Thanks!

**Comment by jacobtnyoung** [comment]
Hi @AliciaSettles! 

Did you set the `input$` operation? If so, can you show the code for this?

Without seeing your code it is hard to diagnose the issue.

**Comment by AliciaSettles** [comment]
Hi!

I went ahead and sent you the .rmd file. I believe I did use that, but then again I could be mistaken! Thanks!!

**Comment by jacobtnyoung** [comment]
Hi @AliciaSettles 

The `selectInput()` function and the r`enderPlot({})` function have errors. Take a look and the revisions to the .Rmd file you sent.

**Comment by AliciaSettles** [comment]
Hi,
I'm still having trouble figuring out where the error is in selectInput() is going wrong, I did put renderPlot({}) around the input$ which helped. Also, not all my teams are showing up in the dynamics and the graph is without detail. I didn't receive anything with the revisions, I'm following alongside the lab instructions, yet I still cannot seem to get it correct.

Thanks!

**Comment by jacobtnyoung** [comment]
Hi @AliciaSettles . I send an email to your .asu email. I resent it. You should have it now.

**Comment by AliciaSettles** [comment]
Thank you so much, that definitely helped me understand more!

**Comment by jacobtnyoung** [comment]
Hi @AliciaSettles! Great. Glad to help!
