### ISSUE TITLE
Lab 4-unexpected symbol

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#25]
```selectInput(inputID = "my_team"
  
  label = "Select a team:"```
Error: unexpected symbol in:
"  
  label"

I erased it and re-wrote it, I took out the colon after "Select a team."  I am pretty sure that the label needs to be in quotes so I am confused that I am getting this error message and makes me very nervous for the rest of my document....I would love your thoughts. Thanks

**Comment by danafuller** [comment]
It didn't format correctly above....
```
selectInput(inputID = "my_team"
  
  label = "Select a team:"
```

**Comment by danafuller** [comment]
I also added commas and took them out and nothing changed

**Comment by jacobtnyoung** [comment]
Hi @danafuller!

You need `inputId` not `inputID`. Note the difference in capitalization.

**Comment by danafuller** [comment]
Oh my goodness, duh.  Thank you!

**Comment by danafuller** [comment]
I am having the same issue after fixing it.
```
selectInput(inputId = "my_team"
  
  label = "Select a team:"
```
Error: unexpected symbol in:
"  
  label"

**Comment by jacobtnyoung** [comment]
Hi @danafuller! I say "Oh my goodness, duh" at least twice a day :)

**Comment by jacobtnyoung** [comment]
Hi @danafuller,

You need a comma after `"my_team"` and after `"Select a team:"`. See below: 

```
selectInput(inputId = "my_team" ,
  
  label = "Select a team:" ,

```

**Comment by danafuller** [comment]
I guess I switched them so many times back and forth the first round when my inputId was wrong that I forgot it was necessary there.  Thank you.  The good news is that the document ran and I just need to do the legend so hopefully you won't be inundated with my questions.

**Comment by jacobtnyoung** [comment]
@danafuller, sometimes it is easiest to just go back to the template and run it. Then, gradually add things. That way you can identify where the error is occurring.

**Comment by danafuller** [comment]
Thanks.  That's good advice.
