### ISSUE TITLE
Mean review-Lab #5

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#27]
Which is the correct code for finding the proportion of accidents that occur on Monday?

I saved accidents that occurred on Monday as an object named Mon.accidents.  I am assuming that Incidentid captures all accidents?
```
mean(Mon.accidents) #or mean
(Mon.accidents/dat$Incidentid)
#or
 mean(dat$Incidentid[Mon.accidents])
```

**Comment by jacobtnyoung** [comment]
Hi @danafuller! You need the length of each object for the proportion.

**Comment by danafuller** [comment]
Thanks Dr. Young,

I just need a little more clarification.  I understand in the context of
the example that uses cylinders and sorting through the cars in mtcars
defining the length of cylinders as 6, etc.  In our question, are we
defining the length as the values that occur on Monday?
mean(dat$Incidentid == Monday)  If so, how does one give the variable Harm
a length?

Thanks for any clarification!

Dana

**Comment by jacobtnyoung** [comment]
Hi @danafuller. Just a few points of clarification.

This code, `mean(Mon.accidents)`, will take the mean of the values of the object `Mon.accidents`, however you have defined it. It will return a vector.

This code, `(Mon.accidents/dat$Incidentid)`, will divide each value of `Mon.accidents` by each value of `dat$Incidentid`. So that will also return a vector.

This code, `mean(dat$Incidentid[Mon.accidents])`, will take the mean of the object `dat$Incidentid`. Without seeing how you have defined `Mon.accidents` I can't tell you exactly what it will return. But, it will be a scalar (i.e. a single number).

**Comment by jacobtnyoung** [comment]
@danafuller, note that the variable `Incidentid` is a unique id for the incident.

**Comment by jacobtnyoung** [comment]
@danafuller, compare these two statements:

```
mean(dat$Incidentid == Monday) # your code above
```

and this one: 

```
Monday <- dat$day == "Mon" # create a logical vector meeting the condition.
mean( Monday ) # take the mean.
```

In your statement, R will return the mean of `Incidentid`, which is the mean of the unique ids. 

See the difference?

**Comment by danafuller** [comment]
Thank you for that.  This is what I did:
```
Mon.accidents <- dat$Incidentid == "Monday"
```
Would that have worked?  It seems like it should capture all of the
accidents that occurred on Monday.  Or perhaps it is combining two things
while your code is cleaner and just separating out Monday exclusively and
not accidents as well.

**Comment by jacobtnyoung** [comment]
@danafuller, for your second question the lab instructions say: "We will define 'harm' as any accident that causes at least one injury OR fatality. You need to define a new variable in your dataset that indicates whether accidents caused harm or not.".

So, you would want to translate the sentence above into a logical statement.

The pseudo code would look something like:

harm  <- an accident where there is more than zero injuries OR an accident with more than zero fatalities

Then, you would replace the sentence with the variables and the logical statement:

`harm  <- dat$Totalinjuries > 0  | dat$Totalfatalities > 0`

That then gives you a logical vector meeting the condition.

**Comment by jacobtnyoung** [comment]
> 

@danafuller there are two differences. First, you are using a different variable. Look at the values of the variable `Incidentid`. Also, there is a difference between `"Monday"` (which is a character) and `Monday` (which R reads as an object).

**Comment by danafuller** [comment]
I'm sorry, I feel like I am giving you this piecemeal.  I am not confident
in my answers but want to work through it.  This is what I did to define
the new variable Harm which is different from yours.  Can you explain why
this would not be correct or is it just another way to do the same thing?
```
Harm <-dat %>% mutate(Harm=Totalinjuries & Totalfatalities) #new variable
(Aren't they by definition those two variables greater than zero or the
value wouldn't exist there?)
```

**Comment by jacobtnyoung** [comment]
```

Harm <-dat %>% mutate(Harm=Totalinjuries & Totalfatalities) 
#new variable (Aren't they by definition those two variables greater than zero or the value wouldn't exist there?) 

```

You could have the value zero. You will still need a condition that stipulates a logical statement to define the variable.

**Comment by danafuller** [comment]
Thanks for all your help!

**Comment by jacobtnyoung** [comment]
🤙🏼
