### ISSUE TITLE
Lab #5 Create a new table of time of day and age group that reports the proportion of accidents at "7 AM" 

### ISSUE THREAD

**Issue by cdamoah** [Watts-College/cpp-526-fall-2022#28]
dat %>% 
  group_by(hour12, age ) %>% 
  summarize(n = n()) %>%      
  group_by(age) %>%           
  mutate(freq =n/sum(n)) %.>%                
  filter(hour12 == "7AM") %>%
  pander()

The above code gives me this error
Error in dat %>% group_by(hour12, age) %>% summarize(n = n()) %>% group_by(age) %>% : 
could not find function "%.>%"

I have tried all I can but I seem not to know what is going on.

**Comment by cdamoah** [comment]
When  write the code again as
dat%>%
  group_by(hour12, age)%>%
  summarise(n=n())%>%
  mutate(freq =n /sum(n))%>%
  filter(hour12 == "7AM")%>%
  pander()

the result was 
`summarise()` has grouped output by 'hour12'. You can override using the `.groups` argument.
------------ --------- ------- ----------
 **hour12**   **age**   **n**   **freq** 

------------ --------- ------- ----------

**Comment by jacobtnyoung** [comment]
Hi @cdamoah. In the `mutate` statement the code should be `%>%`, so remove the . from your statement.

**Comment by jacobtnyoung** [comment]
```

dat %>%
group_by(hour12, age ) %>%
summarize(n = n()) %>%
group_by(age) %>%
mutate(freq =n/sum(n)) %>%
filter(hour12 == "7AM") %>%
pander()

```

**Comment by cdamoah** [comment]
@jacobtnyoung I have removed the . but till I get nothing. The result shows as

`summarise()` has grouped output by 'hour12'. You can override using the `.groups` argument.

------------ --------- ------- ----------
 **hour12**   **age**   **n**   **freq** 

------------ --------- ------- ----------

**Comment by jacobtnyoung** [comment]
Hi @cdamoah, check the character for 7 AM. It looks like there might be a space. Try this:

```
 filter(hour12 == " 7 AM") %>%
```

**Comment by jacobtnyoung** [comment]
Hi @cdamoah! Note that the code in the instructions has a space before the number for the times with a single digit:

```
time.levels <-
  c( "12 AM", " 1 AM", " 2 AM", " 3 AM", " 4 AM", " 5 AM", 
     " 6 AM", " 7 AM", " 8 AM", " 9 AM", "10 AM", "11 AM", 
     "12 PM", " 1 PM", " 2 PM", " 3 PM", " 4 PM", " 5 PM", 
     " 6 PM", " 7 PM", " 8 PM", " 9 PM", "10 PM", "11 PM" )
```

**Comment by cdamoah** [comment]
Same issue persists even after introducing the space.

**Comment by jacobtnyoung** [comment]
hi @cdamoah. I am getting the table when I run this code:

```
dat %>%
  group_by(hour12, age) %>%
  summarise(n=n()) %>%
  mutate(freq = n /sum(n)) %>%
  filter(hour12 == " 7 AM") %>%
  pander()
```

If you are getting a blank table, then you should rerun your script using the lab instructions. Something might have been written over.

**Comment by cdamoah** [comment]
I am still facing the challenge. Now the code

dat %>% 
  count(hour12, age ) %>% 
  group_by( hour12 ) %>% 
  mutate( n.hour12 = sum(n) )%>%
  mutate(prop = n/n.hour12) %>%
  filter(hour12 == " 7AM")  

gives me this 
 A tibble: 0 × 5
# Groups:   hour12 [0]
# … with 5 variables: hour12 <fct>, age <fct>, n <int>, n.hour12 <int>, prop <dbl>
# ℹ Use `colnames()` to see all variable names

**Comment by jacobtnyoung** [comment]
Hi @cdamoah I am having a hard time reproducing the error on my end. Let me look through your .Rmd file you posted.
