### ISSUE TITLE
Lab #5 Part 1 Question 3

### ISSUE THREAD

**Issue by alinemaestas** [Watts-College/cpp-526-fall-2022#29]
dat %>% 
  group_by(day) %>% 
  summarize(Accidents = n(),
            Injuries = sum(Totalinjuries), 
            Fatalities = sum(Totalfatalities))
mon_prop<- sum(dat$day =="Mon" & dat$Totalinjuries) + sum(dat$day=="Mon" & dat$Totalfatalities)
sum(dat$day=="Mon" & dat$Totalinjuries> 0)

I am trying to get the total of Monday's injuries and fatalities but it's totaling 1225 from line 191 . But when I look at the chart and add up the two 1644 and 13, it equals 1657. So I started to try a different code on line 192, but I am still getting the same total as line 191 and not the numbers from the chart.
To calculate the proportion of accidents on Monday, I was trying to add Monday's injuries and fatalies and then divide that by the total of Monday's accidents of 4094.
Am I using the wrong combination?
<img width="1070" alt="Screen Shot 2022-09-20 at 10 14 21 PM" src="https://user-images.githubusercontent.com/112110787/191565910-380a6e80-b04d-47d1-bb23-f22a2864a316.png">

**Comment by jacobtnyoung** [comment]
Hi @alinemaestas. Try this:

```
mondays <- dat[dat$day == "Mon", ]
mean( mondays$Totalfatalities > 0 | mondays$Totalinjuries > 0, na.rm = TRUE )
```

**Comment by cjstewa9** [comment]
Can you do this using pipes and data verbs? I can't figure out why the code I'm using doesn't work. 

```r
dat %>% filter( day == "Mon") %>% mean( Totalinjuries > 0 | Totalfatalies > 0, na.rm = TRUE) 
```
I get the "argument is not numeric or logical: returning NA[1] NA" error.

**Comment by lecy** [comment]
When you pipe objects you are placing the return object from the previous function as the first argument in the next function. 

So this:

```
dat %>% mean( Totalinjuries > 0 | Totalfatalies > 0, na.rm = TRUE) 
```
Would be equivalent to this: 

```
mean( dat, Totalinjuries > 0 | Totalfatalies > 0, na.rm = TRUE) 
```
Does that look right? You will get an error because you are referencing Totalinjuries instead of dat$Totalinjuries, etc. 

Try a dplyr verb - they always expect a data frame as the first argument: 

```
dat %>% summarize( ave= mean( Totalinjuries > 0 | Totalfatalies > 0, na.rm = TRUE)  )
```

**Comment by jacobtnyoung** [comment]
Thanks @lecy
