### ISSUE TITLE
Lab 5: Accidents by Hour and Age

### ISSUE THREAD

**Issue by cjstewa9** [Watts-College/cpp-526-fall-2022#30]
I'm pretty confused on this question. I don't understand the logic of all the code provided in the .rmd and instructions. As a result I can't tell if this table is correct, wrong, or if the assignment is asking for something more. 
```r
dat %>% 
  group_by( hour12, age ) %>%
  summarize( n = n()) %>% 
  group_by( age ) %>%
  mutate( n.age = sum(n) ) %>%
  mutate( prop = n / n.age ) %>%
  filter( hour12 == "7 AM" )
```

**Comment by jacobtnyoung** [comment]
Hi @cjstewa9. This is the correct setup for the code. The only issue is that the instructions code time as `" 7 AM"`, not `"7 AM"`. That one space makes the difference in how it reads the character.
