### ISSUE TITLE
Lab #6-left join

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#31]
This is the aggregate salaries by team and year
```
total.sal <- Salaries %>% group_by(teamID, yearID) %>% summarise(player=n(), total.cost=sum(salary.adj, na.rm = TRUE))
```
When I use this object to join the data sets, it doesn't include any values for total cost which I think I need to proceed.  In addition total.sal doesn't have a W column.
```
mutate(total.sal, cost.per.win= total.sal/W/100000)
```
Do I need to do an additional left join with total.sal and maybe team.sal so that there is a W column?

**Comment by danafuller** [comment]
Additionally, the columns in total.sal are ordered teamID, then yearID.  However, in team.sal, they are ordered yearID, igID, teamID.  Do I need to arrange them to match before I proceed?

**Comment by jacobtnyoung** [comment]
> Additionally, the columns in total.sal are ordered teamID, then yearID. However, in team.sal, they are ordered yearID, igID, teamID. Do I need to arrange them to match before I proceed?

@danafuller, that is correct. You need to do `group_by( yearID, teamID )`.

**Comment by jacobtnyoung** [comment]
> This is the aggregate salaries by team and year
> 
> ```
> total.sal <- Salaries %>% group_by(teamID, yearID) %>% summarise(player=n(), total.cost=sum(salary.adj, na.rm = TRUE))
> ```
> 
> When I use this object to join the data sets, it doesn't include any values for total cost which I think I need to proceed. In addition total.sal doesn't have a W column.
> 
> ```
> mutate(total.sal, cost.per.win= total.sal/W/100000)
> ```
> 
> Do I need to do an additional left join with total.sal and maybe team.sal so that there is a W column?

@danafuller, your are correct in that you need to merge the salaries data with the `Teams` data to get the W variable.

**Comment by danafuller** [comment]
Thank you for the clarification.  I was also wondering why there aren't any values for total.cost? Did I do something wrong?
```
 total.sal <- Salaries %>% group_by(teamID, yearID) %>% summarise(player=n(), total.cost=sum(salary.adj, na.rm = TRUE))
```

**Comment by danafuller** [comment]
I figured it out!

**Comment by jacobtnyoung** [comment]
👏🏼👏🏼👏🏼

**Comment by Mash-ea** [comment]
> mutate(total.sal, cost.per.win= total.sal/W/100000)



> Thank you for the clarification. I was also wondering why there aren't any values for total.cost? Did I do something wrong?
> 
> ```
>  total.sal <- Salaries %>% group_by(teamID, yearID) %>% summarise(player=n(), total.cost=sum(salary.adj, na.rm = TRUE))
> ```

why isnt there any values for total.cost ? when you merge Salaries and full teams table ?

**Comment by jacobtnyoung** [comment]
I don't see anything problematic when I run it. 

Try restarting with a fresh workspace and running the code.

```

library( Lahman )
data( People )
data( Batting )
data( Salaries )
data( Teams )
library( dplyr )


Salaries <- 
  Salaries %>% 
  mutate( salary.adj = salary*(1.03)^( max(yearID) - yearID ) )

total.sal <- 
  Salaries %>% 
  group_by(teamID, yearID) %>% 
  summarise(player=n(), 
            total.cost=sum(salary.adj, na.rm = TRUE)
            )

```

**Comment by Mash-ea** [comment]
when i merge Salary and Teams in step 2...not sure if thats correct -
team_sals <- left_join(Teams,total_sal, by = c("yearID","teamID"))

shouldnt the resulting data frame include the adjusted team budget vector ? The column appears but without any values 

then on step 3- guess after piping the merged Salary & Team data and then trying to mutate

mutate(cost.per.win= total.cost/W/100000)

I see W column on step2 dataframe- but when i run it R gives the Object W not found- do i have to create another dataframe, no clue here

**Comment by jacobtnyoung** [comment]
```

library( Lahman )
data( People )
data( Batting )
data( Salaries )
data( Teams )
library( dplyr )


Salaries <- 
  Salaries %>% 
  mutate( salary.adj = salary*(1.03)^( max(yearID) - yearID ) )

total_sal <- 
  Salaries %>% 
  group_by( yearID, teamID ) %>% 
  summarise(player=n(), 
            total.cost=sum(salary.adj, na.rm = TRUE)
            )

 team_sals <- left_join(Teams,total_sal, by = c("yearID","teamID"))

```

The vector was returning NA values because the order of the `by` statement was reversed with the sorting of the object.

When you correct this, the column `W` is now populated.

**Comment by danafuller** [comment]
I think you may need to place total.cost right after the summarise function
for it to work properly.
