### ISSUE TITLE
Join Salaries & Teams

### ISSUE THREAD

**Issue by cdamoah** [Watts-College/cpp-526-fall-2022#32]
dplyr:: left_join(Salaries, Teams, by=c('yearID' = 'yearID', 'teamID' = 'teamID', 'lgID' = 'lgID' ) ) %>% 
  pander()    is not giving many results. I want to do the left join.

**Comment by jacobtnyoung** [comment]
Hi @cdamoah. Take a look at the way the ids are structured in the data. Use `head(Salaries)` and `head(Teams)`. You will see that they are not structured the same in terms of the compound ids.

**Comment by cdamoah** [comment]
@jacobtnyoung When I use   full_join(total.sal, Teams,  by= c("yearID", "teamID")) %>% print()  I don't get W showing in the data but total.cost shows

but when I use merge (total.sal, Teams,  by= c("yearID", "teamID")) %>% print() total.cost turns out to be 0 and then W appears in the data. 

I am confused and don't know what to do.

**Comment by jacobtnyoung** [comment]
Hi @cdamoah. I can't reproduce the example if you don't provide the code to set up the objects. Like the `total.sal` object you mention.

Please review the instructions for using Github Issues to best facilitate helping you.
