### ISSUE TITLE
Final Dashboard

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#33]
'''
selectInput(inputId = "time.of.day", 
            label = h4("[Time of Day]"), 
            choices = c("Morning Commute", 
                        "Work", 
                        "School Pickup", 
                        "Night", 
                        "Midnight to Dawn"),
            selected = "Morning Commute")
'''
I am using this as one of my tabs, but I was wondering if I could put it on a slider input instead by also using the numerical assignments that were done in the preprocessing?  Or should I just leave it this way?  Is it ok for my extra tabs to all be select inputs?  I want to look at age categories, substances, and time of day.

**Comment by danafuller** [comment]
Actually, I think it should be a checkboxInput as written above, but interested to know if possible to have on a slider with numerical assignment.  Disregard my last question-I have 3 checkbox inputs and this last one of time of day as a questionable format that I would love your input.  Thanks so much!

**Comment by jacobtnyoung** [comment]
Ok good! Sounds like you figured it out @danafuller!

**Comment by danafuller** [comment]
I sent you an email with my completed almost Dashboard for some feedback.  Thank you so much!
