### ISSUE TITLE
Output not show data points 

### ISSUE THREAD

**Issue by courtney-haasch** [Watts-College/cpp-526-fall-2022#35]
Hi, 

For one of my tabs I am unable to see data points. I am attempting to show the age, gender, and potential substance. When I knit it I see data points on the map for No Apparent Influence but I see no data points for alcohol, drugs, or alcohol and drugs. 

[Age, Gender, and Substance]
=====================================  

Inputs {.sidebar}
-------------------------------------
sliderInput(inputId = "d1age", 
            label = h4("Driver 1 Age"), 
            min = 15, 
            max = 100, 
            value = c(18,36) )

sliderInput(inputId = "d2age", 
            label = h4("Driver 2 Age"), 
            min = 15, 
            max = 100, 
            value = c(18,36) )

selectInput(inputId = "d1gender", 
            label = h4("Driver 1 Gender"), 
            choices = c("Male",
                        "Female", 
                        "Unknown"), 
            selected = "Male")

selectInput(inputId = "d2gender", 
            label = h4("Driver 2 Gender"), 
            choices = c("Male",
                        "Female", 
                        "Unknown"), 
            selected = "Male")

selectInput(inputId = "d1.substance", 
            label = h4("Driver 1 Substance"), 
            choices = c("No Apparent Influence",
                        "Alcohol", 
                        "Drugs", 
                        "Alcohol and Drugs"), 
            selected = "No Apparent Influence")
 
selectInput(inputId = "d2.substance", 
            label = h4("Driver 2 Substance"), 
            choices = c("No Apparent Influence",
                        "Alcohol", 
                        "Drugs",  
                        "Alcohol and Drugs"), 
            selected = "No Apparent Influence")

**Outputs**
### [Accidents by Age, Gender and Substance]

```{r}

renderLeaflet({
  
  # WHERE UNIQUE IDs ARE USED TO FILTER YOUR DATA
  
      # Function 'filter()' from package 'dplyr' filters data ccording to user inputs.
      # Note that the selected values in each widget above is "called" here with 'input$' and its ID
      # Each input ID must correspond to an existing variable and the input values must also match those of the variable



  d5 <- dat %>%
    filter(Age_Drv1 >= input$d1age[1],
           Age_Drv1 <= input$d1age[2], 
           Age_Drv2 >= input$d2age[1],
           Age_Drv2 <= input$d2age[2], 
           Gender_Drv1 %in% input$d1gender, 
           Gender_Drv2 %in% input$d2gender, 
           AlcoholUse_Drv1 %in% input$d1.substance,
           AlcoholUse_Drv2 %in% input$d2.substance,
           DrugUse_Drv1 %in% input$d1.substance,   
           DrugUse_Drv2 %in% input$d2.substance) 

  

  # IF CREATING A MAP, YOU CAN IGNORE EVERYTHING BELOW THIS COMMENT
  
  d5$col.vec <- ifelse(test = d5$nohurt, 
                       yes = "gray20", 
                       no = ifelse(test = d5$inj, 
                                   yes = "steelblue", 
                                   no = "darkorange")) 
  
  point.size <- d5$Totalinjuries + d5$Totalfatalities

  crash.details <- paste0("Time: ", d5$DateTime, "<br>",
                          "Total Fatalities: ", d5$Totalfatalities, "<br>",
                          "Total Injuries: ", d5$Totalinjuries, "<br>",
                          "Collision type: ", d5$Collisionmanner)
  
  tempe <- leaflet() %>% 
    addProviderTiles("CartoDB.Positron") %>%
    setView(lng = -111.9278, 
            lat = 33.39951, 
            zoom = 13)
  
  
  addCircles(tempe, 
             lng = d5$Longitude, 
             lat = d5$Latitude,
             fillColor = d5$col.vec, 
             fillOpacity = 0.5, 
             stroke = FALSE, 
             radius = 50 * (1 + 0.33 * point.size),
             popup = crash.details)

})

**Comment by jacobtnyoung** [comment]
Hi @courtney-haasch. Please email me the .Rmd file. It is easier to work through it there.

**Comment by courtney-haasch** [comment]
Hi @jacobtnyoung , thanks just sent the email.

**Comment by jacobtnyoung** [comment]
Hi @courtney-haasch. I sent a revision back.
