### ISSUE TITLE
Shiny APP following path of document

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#36]
Is anyone else having problems connecting their document to the Shiny App?
```
library(rsconnect)
     rsconnect::deployApp('C:/Users/danaf/OneDrive/Documents/cpp-526-Final Dashboard-DFuller')
```
I get this error, but I know that file exists!
Error in rsconnect::deployApp("C:/Users/danaf/OneDrive/Documents/cpp-526-Final Dashboard-DFuller") : 
  C:\Users\danaf\OneDrive\Documents\cpp-526-Final Dashboard-DFuller does not exist
> 
>

**Comment by jacobtnyoung** [comment]
@danafuller did you try switching the `/` to `\` or the reverse?

**Comment by danafuller** [comment]
I did and I got this error:
Error: '\U' used without hex digits in character string starting "'C:\U"

I think I need to get this to work to have a link, correct?

**Comment by jacobtnyoung** [comment]
Hi @danafuller. No worries, I see you are trying to get this to work.
