### ISSUE TITLE
Collision manner and Violations tab

### ISSUE THREAD

**Issue by Mash-ea** [Watts-College/cpp-526-fall-2022#37]
please help with this tab....Do I have to Include all those choices ?

checkboxGroupInput ("Collisionmanner",                         
            label = h4("Type(Collisionmanner)"),
            choices = c("Rear End",                               
                        "Left Turn",                             
                        "ANGLE (Front To Side)(Other Than Left Turn)", 
                        "Sideswipe Same Direction",
                        "Single Vehicle",
                        "Other",
                        "Unknown",
                        "Head On",				
		                    "Rear To Side",	
                        "Sideswipe Opposite Direction"),
              selected = "Rear End")                                   

checkboxGroupInput("Violations1", 
            label = h4("Driver1")) 
                   choices = c("Speed To Fast For Conditions", 
                   "Failed To Yield Right Of Way", 
                   "Disregarded Traffic Signal", 
                   "Unsafe Lane Change",
                   "Inattention Distraction",
                   "Made Improper Turn",
                   "Followed Too Closely",
                   "Failed To Keep In Proper Lane",
                   "Knowingly Operated With Faulty Missing Equipment",
                   "Passed In No Passing Zone",
                   "Disregarded Pavement Markings",
                   "Electronic Communications Device",
                   "Other Unsafe Passing",
                   "Did Not Use Crosswalk",
                   "Ran Stop Sign", 
                   "Exceeded Lawful Speed",
                   "No Improper Action",
                   "Other",
                   "Unknown")
selected = ("Unsafe Lane Change")

checkboxGroupInput("Violations2", 
            label = h4("Driver2")) 
          choices = c("Speed To Fast For Conditions", 
                   "Failed To Yield Right Of Way", 
                   "Disregarded Traffic Signal", 
                   "Unsafe Lane Change",
                   "Inattention Distraction",
                   "Made Improper Turn",
                   "Followed Too Closely",
                   "Failed To Keep In Proper Lane",
                   "Knowingly Operated With Faulty Missing Equipment",
                   "Passed In No Passing Zone",
                   "Disregarded Pavement Markings",
                   "Electronic Communications Device",
                   "Other Unsafe Passing",
                   "Did Not Use Crosswalk",
                   "Ran Stop Sign", 
                   "Exceeded Lawful Speed",
                   "No Improper Action",
                   "Other",
                   "Unknown")
selected = ("Exceeded Lawful Speed")   

renderLeaflet({
  
  d5 <- dat %>%
    filter(Collisionmanner %in% input$collisionmanner,
      Violation1_Drv1 == input$violations1,
      Violation1_Drv2 == input$violations2,)   
  

IM GETTING THE ERROR BELOW IN MY CONSOLE...AND AN error :object Object] on the map, 

Output created: C:/Users/edwar/AppData/Local/Temp/RtmpM5am9m/file222420d6398b/cpp-526-DashboardIsolatedFoti.html
Warning: Error in filter: Problem while computing `..2 = Violation1_Drv1 == input$violations1`.
✖ Input `..2` must be of size 25293 or 1, not size 0.
  115: <Anonymous>
  114: signalCondition
  113: signal_abort
  112: abort
  111: <Anonymous>
  110: signalCondition
  109: signal_abort
  108: abort
  107: dplyr_internal_error
  106: mask$eval_all_filter
  104: filter_eval
  103: filter_rows
  102: filter.data.frame
  101: filter
  100: %>%
   99: ::
htmlwidgets
shinyRenderWidget [<text>#5]
   98: func
   85: renderFunc
   84: output$out35e64cc204fc4efd
    3: <Anonymous>
    1: rmarkdown::run
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.  
  
`

**Comment by jacobtnyoung** [comment]
@Mash-ea It is hard to diagnose the problem without seeing the .Rmd file. You can send it to me, but I will not be able to look it over until Sunday.

**Comment by jacobtnyoung** [comment]
@Mash-ea check the case of your inputId variables to make sure they match.
