### ISSUE TITLE
Dashboard Rate of Harm Error

### ISSUE THREAD

**Issue by evanpiepho** [Watts-College/cpp-526-fall-2022#38]
Hello,

I am just finishing up my dashboard, but I cannot seem to work this out. I created two tabs in my dashboard for road conditions and details about accidents. The problem I am encountering is that some of the conditions are too obscure; combinations of, say, "Left Turn"/"Failed To Yield Right Of Way"/"Followed Too Closely" for collision manner, driver 1 violation, and driver 2 violation, respectively, don't exist. This is only a problem because the code for rate of harm is as follows:

 `rate.of.harm <- round(length(which(d2$harm == "Harm")) / count(d2), 3)`

If there is no accident for a specified set of conditions, `count(d2)` will be zero and produce the output `Inf`. 

Here is the code for the valueBox:
` valueBox(rate.of.harm,  
           icon = "fa-hospital",
           color = ifelse(test = rate.of.harm > 0.5, 
                           yes = "#f9c8a7", 
                           no = "primary"))`

And the `Inf` value produces an error when running the dashboard:

![image](https://user-images.githubusercontent.com/111325751/194680743-156863b8-5aa1-414a-8303-e6aaebdc51a9.png)

I tried everything I could think of, including creating conditional variables based on whether `count(d2)` equaled zero or not and running a different calculation based on that status. I just couldn't make it work. 

Any help is appreciated, as it's the only thing I have left to finish.

**Comment by jacobtnyoung** [comment]
@evanpiepho, you can add an additional argument to define the value `Inf` as zero. This would make the rate of harm zero though. So, you might think about whether that makes sense to do.

**Comment by jacobtnyoung** [comment]
@evanpiepho, if you can't figure it out don't worry. Go ahead and post the assignment and I can take a look.

**Comment by evanpiepho** [comment]
@jacobtnyoung thanks for your response! I didn't even consider that. But I think you're right that setting the rate of harm to zero artificially isn't necessarily the correct solution. A null/NA value would be more appropriate, it seems. I still have a little bit of time, so I'll try to tinker some more and see if I can't come up with another solution. Thanks again!

**Comment by jacobtnyoung** [comment]
Hi @evanpiepho, you could have it return a character like `"Combination of entries does not exist"` or something. Like a sort of warning.
