### ISSUE TITLE
test

### ISSUE THREAD

**Issue by lecy** [Watts-College/cpp-526-fall-2022#5]
test

**Comment by lecy** [comment]
Have you subscribed to all notifications? 

![image](https://user-images.githubusercontent.com/1209099/179854550-711432ad-d3d1-41b3-b3e8-6d613ed66f3c.png)

**Comment by jacobtnyoung** [comment]
I did. I am getting the emails, but they are not diverting to a folder. I will keep working on it. Thanks for the help!
