### ISSUE TITLE
Mortgage Payment Calculation

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#6]
This is what I wrote in R to calculate the mortgage payment and it isn't correct.  If R follows the order of operations and handles the parenthesis first and then goes left to right because the rest is multiplication and division, how does one account for that?  Am I missing something obvious??

100000*0.05/12/1-(1 + 0.05/12)-360

**Comment by jacobtnyoung** [comment]
Hi @danafuller! Good question, you are missing something but it might not be obvious. Take a look at the formula for the mortgate payment. The denominator has "months" in the exponent. So, you need to modify your equation accordingly. Take a look at the ```^``` character in the script building a function for the equation.

**Comment by jacobtnyoung** [comment]
Let me know if you still have questions. 👍🏼

**Comment by danafuller** [comment]
I didn't realize that the month was raised to the power.  Easy fix.  Thank you so much!

**Comment by jacobtnyoung** [comment]
Great!
