### ISSUE TITLE
Saving Lab with html

### ISSUE THREAD

**Issue by cdamoah** [Watts-College/cpp-526-fall-2022#8]
<img width="1234" alt="Lab1" src="https://user-images.githubusercontent.com/111333023/186251468-10932c09-b033-42bb-a85a-642075a8d324.png">

My work appears as it is in the attached picture after I save with .html and I try to preview. How do I get it to appear well as the Rmarkdown document? @jacobtnyoung I would be grateful if you could assist.

**Comment by jacobtnyoung** [comment]
Hi @cdamoah ! It is hard to see what exactly the issue is here. You can do a few things:

1. Download the lab template again and knit it without making any edits. You should get an .html file that looks right.
2. If step 1 works, then start adding your code back into the template and try to see where the error occurs.

Let me know if you are still running into issues.

**Comment by cdamoah** [comment]
> 

I got something and I have sent it via Canvas. Hopefully, it is what we are required to submit. Thank you.

**Comment by jacobtnyoung** [comment]
Hi @cdamoah! Looks like you got it to work. I checked what you submitted on Canvas and the formatting is fine. Did you figure out what the issue was?

**Comment by courtney-haasch** [comment]
Hi @jacobtnyoung , 
I am having issues creating the HTML. 
I receive the following error message: 

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
Error in setwd(wd) : character argument expected


I have had this message come up before and I am not sure why it is happening again?

**Comment by jacobtnyoung** [comment]
Hi @courtney-haasch, 

Did you try running the template prior to making any edits? That is, download the template and knit it.

It looks like there is an issue with trying to access a directory. Do you have an security restrictions on the computer your using?

**Comment by jacobtnyoung** [comment]
@courtney-haasch are you using a mac? If so, check this page:

https://www.symscape.com/node/1727

**Comment by jacobtnyoung** [comment]
Hi @cdamoah it looks like you were able to solve this?

**Comment by cdamoah** [comment]
> 

Yes, I was able to resolve mine. I think the issue was saving the file with the extension html before knitting it. When I reverted it, back to RMD file, it worked, and then I could save my html file.

**Comment by jacobtnyoung** [comment]
Great!
