### ISSUE TITLE
questions 5 and 6 optional sections. 

### ISSUE THREAD

**Issue by cjstewa9** [Watts-College/cpp-526-fall-2022#9]
I'm a bit stuck on the optional sections of questions 5 and 6 (use additional functions to narrow your results). 

For question 5, to determine which neighborhood has the most tax parcels you use:

```r

table(dat$neighborhood)

```

When the optional question asks you to narrow your results, I'm assuming it means have R output only the neighborhoods with the most parcels. I'm not sure what the code is to do this. 

For question 6 (and also question 5), I'm not sure what "narrow" means. You can reduce the width of the table R outputs with:

```r

table( dat$neighborhood, dat$land_use == "Vacant Land" )

```

But I'm not sure this is what you're looking for.

**Comment by jacobtnyoung** [comment]
Hi @cjstewa9! 

Question 5: You can use the `table()` function and just locate the largest value. Or, you can use the `which.max()` function.

I am not seeing on the [lab instructions](https://watts-college.github.io/cpp-526-fall-2022/labs/lab-01-instructions.html) where you are getting the term narrow. Could you be more specific? The code you have will show the frequency of parcels by neighborhood just for vacant land.

**Comment by cjstewa9** [comment]
They're in the .rmd template. For questions 5 and 6, there's optional sections that say "Use additional functions to narrow your results." I'm not sure what this means.

**Comment by jacobtnyoung** [comment]
I see:

# (Optional) use additional functions to narrow your results

This is asking you to see whether you can combine the functions to produce fewer dimensions of the table. 

Does that make sense?

**Comment by cjstewa9** [comment]
Kind of. When you say dimensions, do you mean the number of columns or rows in the table? 

So for number five, you would need to display only the neighborhoods with the most parcels? What would be the code for this?

For number six, 

```r

table( dat$neighborhood, dat$land_use == "Vacant Land" )

```

reduces the number of categories shown. Is that what you're getting at?

**Comment by jacobtnyoung** [comment]
"So for number five, you would need to display only the neighborhoods with the most parcels? What would be the code for this?"

Can you think of a function that you can wrap around your existing statement that would do this?

**Comment by jacobtnyoung** [comment]
For your second question, yes that is what I am getting at.
